INSERT INTO coordinador (Coorid, password, nombre, apellido, rol) VALUES (12345678, '123', 'Juan', 'Perez', 'COORDINADOR');
INSERT INTO coordinador (Coorid, password, nombre, apellido, rol) VALUES (87654321, '321', 'Maria', 'Lopez', 'COORDINADOR');
INSERT INTO coordinador (Coorid, password, nombre, apellido, rol) VALUES (24681012, '246', 'Pedro', 'Garcia', 'COORDINADOR');

INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (123456789, 'pass', 'diego', 'cediel', 'Estudiante', 'correo1@example.com','345678','AAAA3', 'Activo', 180, 175, 125, 90, 110, 138, 122, 148, 1);
INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (177777778, 'mmcc', 'michi', 'alvares', 'Estudiante', 'correo1@example.com','345678','AAAA4', 'Activo', 180, 175, 145, 100, 178, 123, 124, 118, 2);
INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (188888889, 'ccc123', 'sergio', 'palomo', 'Estudiante', 'correo1@example.com','345678','AAAA3', 'Activo', 167, 175, 155, 151, 160, 158, 152, 148, 3);
INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (122222224, '12121', 'jorge', 'jaimes', 'Estudiante', 'correo1@example.com','345678','AAAA4', 'Activo', 110, 175, 112, 100, 178, 123, 124, 118, 1);
INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (133332225, '321', 'solo', 'diaz', 'Estudiante', 'correo1@example.com','345678','AAAA5', 'Anulado', 1, 1, 1, 1, 1, 1, 1, 1, 1);
INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (165788768, 'dede', 'maicol', 'cubides', 'Estudiante', 'correo1@example.com','345678','AAAA4', 'Activo', 180, 175, 145, 100, 178, 123, 124, 118, 3);
INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (113784567, '412312', 'nicolas', 'novoa', 'Estudiante', 'correo1@example.com','345678','AAAA5', 'Activo', 145, 147, 154, 160, 151, 166, 152, 162, 1);
INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (113788778, 'asas', 'nathalia', 'rodriguez', 'Estudiante', 'correo1@example.com','345678','AAAA4', 'Activo', 110, 175, 135, 100, 178, 123, 124, 118, 3);
INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (104444456, 'sergio', 'lina', 'rojas', 'Estudiante', 'correo1@example.com','345678','AAAA5', 'Activo', 145, 116, 125, 116, 111, 116, 125, 116, 2);
INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (166663444, '1233', 'darha', 'gomez', 'Estudiante', 'correo1@example.com','345678','AAAA4', 'Activo', 180, 115, 145, 100, 138, 123, 124, 118, 1);
INSERT INTO estudiante (Estid, password, nombres, apellidos, rol, correo, telefono, idregistro, estado, puntaje_comunicacion, puntaje_razonamiento, puntaje_lectura, puntaje_competencias, puntaje_ingles, puntaje_proyectos, puntaje_ciencias, puntaje_dis, nivel_ingles)VALUES (103789976, 'xdddd', 'santiago', 'florez', 'Estudiante', 'correo1@example.com','345678','AAAA5', 'Anulado', 1,  1,  1,  1,  1,  1,  1,  1,  1);